apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: node-app
          image: ghcr.io/shahidshabbir-se/kubernetes:latest
          env:
            - name: PGHOST
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: secret
            - name: PGDATABASE
              value: mydb
          ports:
            - containerPort: 3000
